project:
  type: book
  output-dir: docs

book:
  title: "Concepts et applications de l'agriculture de précision"
  author: 
    - name: "Charles Frenette-Vallières"
    # - name: "Nicholas Lefebvre"
  date: today
  date-format: iso
  repo-url: https://github.com/chavalli/agriculture-de-precision/
  downloads: [pdf, epub]
  cover-image: images/cover.png
  chapters:
    - index.qmd
    # - intro.qmd
    - sig.qmd
    - vector.qmd
    - raster.qmd
    - src.qmd
    - carto.qmd
    - analyses-spatiales.qmd
    - interpolation.qmd
    - teledetection.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    toc: true
  pdf:
    documentclass: scrbook
    cover-image: images/cover.png
  epub: 
    cover-image: images/cover.png
